steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk/adk-agent-bug-assist:latest'
      - '.'
      - '-f'
      - 'Dockerfile'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/adk/adk-agent-bug-assist:latest'